### ISSUE TITLE
Fehlermeldung bei Parameter 'def' = Leerstring falls type=boolean

### ISSUE THREAD

**Issue by ArneDoe** [Mic-M/iobroker.createUserStates#1]
Ich habe createUserStates() aufgerufen mit:
```
let mynew = [jsvarname, { name:sName, type:'boolean', read:true, write:true, def:'' }]; 
createUserStates('0_userdata.0', true, mynew);
```
Also mit **def** = Leerstring. Dies ist zwar falsch, kann aber leicht passieren.
Es führt zur Meldung: 
> You are assigning a string to the state "0_userdata.0.test" which expects a boolean. ...

**Getestete Korrekturmoeglichkeit:**
```
            setObject(loopParam[0], obj, function (err) {
                ...
                    let init = null;
                  //if (loopParam[1].def === undefined) {   **** Fehler bei def=''  (bzw. def:'')  ****
                    if (loopParam[1].def === undefined || loopParam[1].def === '') {
                        ...
```
Alle anderen Fälle hast Du ja abgefangen.
Gruß, Arne.

**Comment by Mic-M** [comment]
Hi Arne,
danke für dein Issue.
Die Fehlermeldung selbst ist allerdings in Ordnung. 
Ich habe gerade zuletzt beim Adapter-Programmieren sehr geschätzt, wenn mir eine Funktion einen Fehler wegen falschem Datentyp in einem Input-Parameter ausgegeben hat, denn dann hatte ich vor Aufruf schon ein Datentyp-"Problem".
Ich nehme es aber mal als Enhancement auf, da das Script hier ja sehr "user friendly" sein soll :-)

**Comment by ArneDoe** [comment]
Die Fehlermeldung selbst ist **absolut** in Ordnung.
Danke fürs "enhancen". Andere werden meinen "Fehler" früher oder später auch machen...
